### ISSUE TITLE
[feature] Resolve env vars

### ISSUE THREAD

**Issue by yermulnik** [ASleepyCat/tfswitcher#68]
```bash
> tfswitcher
Module constraint is ~> 1.3.6
Terraform 1.3.10 will be installed to "$HOME/bin/terraform"
Using cached archive at "/home/giermulnik/.cache/tfswitcher/terraform_1.3.10_linux_amd64.zip"
Extracting terraform to "$HOME/bin/terraform"
Error: failed to create file at "$HOME/bin/terraform"

Caused by:
    No such file or directory (os error 2)
```

**Comment by ASleepyCat** [comment]
I've created #70 to implement this feature, see if it works out on your end.

**Comment by yermulnik** [comment]
@ASleepyCat Thanks for the quick turnaround with this.
I'm not good with Rust: should `cargo install tfswitcher` work to pick up the change from #70 or I need to pass some additional args? `--git` and `--rev` look to be what I'm looking for, right? Does `cargo install --git git@github.com:ASleepyCat/tfswitcher.git --rev 30867432c1c803b319e3a9483814681088a24543 tfswitcher` look reasonable?

**Comment by ASleepyCat** [comment]
I would clone the repo, checkout the branch and then run `cargo install --path .`.

**Comment by yermulnik** [comment]
Thanks. Switching TF version worked as expected from `expand-env-vars` branch 🤔
