### ISSUE TITLE
[feature] Install with Homebrew

### ISSUE THREAD

**Issue by yermulnik** [ASleepyCat/tfswitcher#87]
It would be great improvement in user UX and package management for MacOS and Linux users if `tfswitcher` was added to Homebrew core (https://docs.brew.sh/Adding-Software-to-Homebrew) or thirdparty tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) as an interim step on the way to Homebrew core. Thanks.

**Comment by ASleepyCat** [comment]
I actually looked into this a few months ago but ran into issues with the rust-analyzer extension breaking for some reason when I tried installing from `brew`. It looks like that's been fixed in some way now, so I've re-opened my homebrew tap repo so you should be able to install `tfswitcher` with `brew install asleepycat/tap/tfswitcher` now.

**Comment by yermulnik** [comment]
No luck 😢 
```shell
==> Installing tfswitcher from asleepycat/tap
==> cargo install
Last 15 lines from /home/giermulnik/.cache/Homebrew/Logs/tfswitcher/01.cargo:
      # On Arch Linux
      sudo pacman -S openssl
      # On Fedora
      sudo dnf install openssl-devel
      # On Alpine Linux
      apk add openssl-dev

  See rust-openssl documentation for more information:

      https://docs.rs/openssl

  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tfswitcher v0.6.0 (/tmp/tfswitcher-20231225-2959007-9ob301/tfswitcher-0.6.0)`, intermediate artifacts can be found at `/tmp/tfswitcher-20231225-2959007-9ob301/tfswitcher-0.6.0/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/asleepycat/homebrew-tap/issues
```
Attached the `~/.cache/Homebrew/Logs/tfswitcher/01.cargo` log
[01.cargo.txt](https://github.com/ASleepyCat/tfswitcher/files/13766357/01.cargo.txt)

**Comment by ASleepyCat** [comment]
I've added `pkg-config` and `openssl` as dependencies to the formula, try it now.

**Comment by yermulnik** [comment]
Worked now! Thanks 👍🏻

**Comment by yermulnik** [comment]
Would probably worth of adding a mention to `README` 🤔

**Comment by ASleepyCat** [comment]
> Would probably worth of adding a mention to `README` 🤔

There's a PR for that, just wanted to make sure everything was working before merging it.
